[package]
name = "p256verify-not-working"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
p256 = { version = "0.13.2", features = ["ecdsa"] }
